server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: member
          uri: http://localhost:8082
          predicates:
            - Path=/members/**, /memberInfos/**
        - id: device
          uri: http://localhost:8083
          predicates:
            - Path=/devices/**, /deviceInfos/**
        - id: lost
          uri: http://localhost:8084
          predicates:
            - Path=/losts/**, /lostInfos/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: device
          uri: http://device:8080
          predicates:
            - Path=/devices/**, 
        - id: lost
          uri: http://lost:8080
          predicates:
            - Path=/losts/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
